import random

rotulos_questoes = {
    1: "Idade (anos)",
    2: "Sexo",
    3: "Semestre que está cursando",
    4: "Renda familiar",
    5: "Período (1-Diurno / 2-Noturno)",
    6: "Você trabalha?",
    7: "Tempo de estudo diário (horas)",
    8: "Mora com quem?",
    9: "Há quanto tempo utiliza computador?",
    10: "Você costuma acessar a Internet?",
    11: "Quanto tempo estuda na internet (horas)",
    12: "Dispositivo móvel mais acessado",
    13: "Tempo conectado por dia (horas)",
    14: "Você utiliza a internet para trabalho?",
    15: "Você utiliza a internet para conversar com amigos?",
    16: "Você utiliza a internet para conversar com desconhecidos?",
    17: "Você utiliza a internet para acessar e-mail?",
    18: "Você utiliza a internet para pesquisas acadêmicas?",
    19: "Você utiliza a internet para acessar notícias?",
    20: "Você utiliza a internet para fazer compras online?",
    21: "Você utiliza a internet para assistir a vídeos online?",
    22: "Você utiliza a internet para participar de jogos online?",
    23: "Você acredita que a internet atrapalha sua formação?",
    24: "Você considera as redes sociais um ambiente tóxico?",
    25: "Você utiliza a internet para fazer download de conteúdo?",
    26: "O que o computador representa para você?",
    27: "Como você se sente em relação à informática?"
}

# Limites e tipos de respostas
limites = {
    1: lambda: random.randint(17, 27),
    2: lambda: random.choice([1, 2]),
    3: lambda: random.randint(1, 12),
    4: lambda: random.randint(1, 8),
    5: lambda: random.choice([1, 2]),
    6: lambda: random.choice([1, 2]),
    7: lambda: random.randint(0, 8),
    8: lambda: random.choice([1, 2, 3]),
    9: lambda: random.randint(3, 25),
    10: lambda: random.choice([1, 2]),
    11: lambda: random.randint(0, 8),
    12: lambda: random.choice([1, 2, 3]),
    13: lambda: random.randint(1, 10),
    14: lambda: random.choice([1, 2]),
    15: lambda: random.choice([1, 2]),
    16: lambda: random.choice([1, 2]),
    17: lambda: random.choice([1, 2]),
    18: lambda: random.choice([1, 2]),
    19: lambda: random.choice([1, 2]),
    20: lambda: random.choice([1, 2]),
    21: lambda: random.choice([1, 2]),
    22: lambda: random.choice([1, 2]),
    23: lambda: random.choice([1, 2]),
    24: lambda: random.choice([1, 2]),
    25: lambda: random.choice([1, 2]),
    26: lambda: random.choice([1, 2, 3]),
    27: lambda: random.choice([1, 2, 3]),
}

# Mapeamento DE/PARA baseado nas alternativas do questionário
de_para = {
    2: {1: "Masculino", 2: "Feminino"},
    5: {1: "Diurno", 2: "Noturno"},
    6: {1: "Sim", 2: "Não"},
    8: {1: "Só", 2: "Amigos", 3: "Família"},
    10: {1: "Sim", 2: "Não"},
    12: {1: "Celular", 2: "Tablet", 3: "Computador/Notebook"},
    14: {1: "Sim", 2: "Não"},
    15: {1: "Sim", 2: "Não"},
    16: {1: "Sim", 2: "Não"},
    17: {1: "Sim", 2: "Não"},
    18: {1: "Sim", 2: "Não"},
    19: {1: "Sim", 2: "Não"},
    20: {1: "Sim", 2: "Não"},
    21: {1: "Sim", 2: "Não"},
    22: {1: "Sim", 2: "Não"},
    23: {1: "Sim", 2: "Não"},
    24: {1: "Sim", 2: "Não"},
    25: {1: "Sim", 2: "Não"},
    26: {1: "Avanço tecnológico que melhora a vida", 2: "Forma rápida de se comunicar", 3: "Atrapalha, exige mais conhecimento" },
    27: {1: "Entusiasmado, quer saber mais", 2: "Obrigada a aprender", 3: "Acho difícil e complicado"}
}